import {attribute, autoGeneratedHashKey} from "@awslabs-community-fork/dynamodb-data-mapper-annotations";
import {dynamicTableName} from "@pristine-ts/aws";

@dynamicTableName('DOG_TABLE_NAME')
export class DogModel {
    @autoGeneratedHashKey()
    id: string;
    @attribute()
    name: string;
    @attribute()
    race: string;
    @attribute()
    ownerId: string;
    @attribute()
    createdAt: Date;
    @attribute()
    updatedAt: Date;
}
